### ISSUE TITLE
sequence images are missing

### ISSUE THREAD

**Issue by SalmaG98** [climbingdaily/SLOPER4D#19]
I am trying to use your visualization code on seq008_running_001 using the following command:
 `python ./visualization/render_scene.py --draw_smpl --draw_human_pc ./seq008_running_001` 

The code crashes in line 155 of `render_scene.py` with the following error:

```python
  File "./visualization/render_scene.py", line 286, in <module>
    det.run(args.index)
  File "./visualization/render_scene.py", line 155, in run
    origin_img.copy(),
AttributeError: 'NoneType' object has no attribute 'copy'
```

It's loading an image with the path `'./seq008_running_001/rgb_data/seq008_running_001_imgs/4.571233.jpg'` that it cannot find, as the only available rgb_data is the `.mp4` video.. I tried many ffmpeg commands to try to extract frames that match the filenames that are in the pkl file, it seems that timestamps are used for names of frames but I can't figure out the exact command. Can you provide it please?

Thank you for this great work!

**Comment by climbingdaily** [comment]
Hey, you can follow the preprocessing steps here:
https://github.com/climbingdaily/SLOPER4D/tree/main/src

and convert the mp4 video to desired images using the following command:
`# Convert the video to images in one sequence:`
`python src/vid2imgs.py $root_folder`

**Comment by SalmaG98** [comment]
Sorry I figured it out and forgot to update this issue, thank you for this great work and this repo :)

**Comment by climbingdaily** [comment]
Glad to hear that! All the best!
